Class Yazoo.EllisonMoyet Extends %Persistent
{

Property wasBornInBasildon As %Boolean;

Storage Default
{
<Data name="EllisonMoyetDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>wasBornInBasildon</Value>
</Value>
</Data>
<DataLocation>^Yazoo.EllisonMoyetD</DataLocation>
<DefaultData>EllisonMoyetDefaultData</DefaultData>
<IdLocation>^Yazoo.EllisonMoyetD</IdLocation>
<IndexLocation>^Yazoo.EllisonMoyetI</IndexLocation>
<StreamLocation>^Yazoo.EllisonMoyetS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
